

# base image on which custom image is based on
FROM microsoft/windowsservercore



# installing IIS and its related windows feature
RUN powershell -Command  Install-WindowsFeature web-server


CMD powershell -command while ($true) { Start-Sleep -Seconds 3600 }



