# escape=`

# base image on which custom image is based on
FROM microsoft/windowsservercore


# argument sqlPassword used during building of image
# used in changing connection string in web.config
ARG  databaseName="xxxxxxxxx"

# installing IIS and its related windows feature
RUN powershell -Command  Install-WindowsFeature web-server, Web-Default-Doc, `
            Web-Dir-Browsing, Web-Http-Errors, Web-Static-Content, Web-Http-Logging, `
            Web-Request-Monitor, Web-Stat-Compression, Web-Filtering, Web-Windows-Auth, `
            Web-Net-Ext45, Web-Asp-Net45, Web-ISAPI-Ext, Web-ISAPI-Filter, Web-Metabase

# installing .NET 4.5 
RUN ["Powershell", "install-windowsfeature","NET-Framework-45-Core" ]

# creating a new Docker folder
RUN powershell -Command New-Item -Path c:\Website -ItemType Directory -Force

# Registering Nuget as Package source
RUN powershell -Command Register-PackageSource -Name Nuget `
            -Location https://api.nuget.org/v3/index.json `
            -ProviderName Nuget -Trusted -Force -ForceBootstrap 

# Registering Chocolatey as Package source
RUN powershell -Command Register-PackageSource -Name chocolatey `
                -Location http://chocolatey.org/api/v2/ `
                -ProviderName chocolatey -Trusted -Force -ForceBootstrap 



# installing xWebDeploy DSC resources 
RUN powershell -Command install-module -Name xwebdeploy `
                                    -RequiredVersion 1.2.0.0  `
                                    -Force -Confirm:$false -Verbose

# removing default iisstrart.htm file
RUN powershell -Command Remove-Item C:\inetpub\wwwroot\iisstart.htm 

# removing default iisstrart.png file
RUN powershell -Command Remove-Item C:\inetpub\wwwroot\iisstart.png 

# removing default web site website from IIS
RUN powershell -Command Remove-Website -Name 'Default Web Site'

# removing default application pool from IIS
RUN powershell -Command Remove-WebAppPool -Name 'DefaultAppPool'

RUN powershell -Command New-WebAppPool -Name "MVCAppPool"

RUN powershell -Command  New-Website -Name 'MVCWebsite' -Port '9000' -PhysicalPath 'C:\inetpub\MVCAPP\' -ApplicationPool 'MVCAppPool' -Force

# Download Chocolatey installar and install the same
RUN powershell -Command install-package -name webdeploy -ProviderName chocolatey -RequiredVersion 3.5.2 -Force -ForceBootstrap -Verbose

# adding the web application file from deployment folder
ADD \Website C:\Website

# changing the current working directory to deployment folder
WORKDIR C:\\Website

# execute the webdeploy package commandline from deployment folder
RUN C:\Website\OnlinePharmacy.deploy.cmd /Y









